### ISSUE TITLE
Falha na inicialização.

### ISSUE THREAD

**Issue by CentroEducacional-CEC** [Gustavo182000/BLAZE-APOSTAS-BOT#1]
> Microsoft Windows [versão 10.0.19044.2486]
> (c) Microsoft Corporation. Todos os direitos reservados.
> C:\Users\SERVIDOR\Desktop\BLAZE APOSTAS>npm run start
> start
> node index

Infelizmente não sai disso!

**Comment by DinhoNunesLC** [comment]
Aparentemente o projeto foi abandonado!

**Comment by CentroEducacional-CEC** [comment]
Já o fiz, descobri que logo depois de executar npm run start todas as mensagens que estavam na pagina da api do bot, somem! Restado apenas {"ok":true,"result":[]}

E enquanto o bot está ativo, nada que é enviado no grupo/canal é registrado na api! (obs, é um bot e umc anal de teste, já uso ele para testar outras plataformas, então está tudo ok com as permissões do bot!)

**Comment by CentroEducacional-CEC** [comment]
Após algumas tentativas, descobri que o comando tem de ser enviado no "Privado" e não no "Chat" onde o bot enviaria os sinais.
